{
  description = "Elixir development environment with mix2nix for reproducible builds";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      nixpkgs,
      flake-utils,
      ...
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # Elixir version (can be changed to elixir_1_16, elixir_1_15, etc.)
        beamPackages = pkgs.beam.packages.erlang;
        inherit (beamPackages) elixir;

        # Build Elixir application using mix2nix
        # First run: mix2nix > mix.nix (generates dependency manifest)
        # Then use the generated mix.nix for reproducible builds
        buildMixProject =
          {
            pname,
            version,
            src,
            mixEnv ? "prod",
            mixNix ? ./mix.nix,
            ...
          }@args:
          let
            # Load dependencies from mix.nix (generated by mix2nix)
            mixDeps = if builtins.pathExists mixNix then import mixNix { inherit beamPackages; } else [ ];
          in
          beamPackages.mixRelease (
            {
              inherit
                pname
                version
                src
                mixEnv
                ;

              # Dependencies from mix.nix
              inherit mixDeps;

              # Don't fetch deps at build time (use mixDeps instead)
              removeMixDeps = false;

              meta = with pkgs.lib; {
                description = "Elixir application built with Mix and mix2nix";
                platforms = platforms.unix;
              };
            }
            // builtins.removeAttrs args [
              "pname"
              "version"
              "src"
              "mixNix"
            ]
          );
      in
      rec {
        packages = {
          # Build the application as a release
          default = buildMixProject {
            pname = "elixir-app";
            version = "0.1.0";
            src = ./.;
            mixEnv = "prod";
            # mixNix = ./mix.nix;  # Uncomment after generating mix.nix
          };

          # Build documentation
          # Output layout:
          #   $out/index.html              — root index linking all sections
          #   $out/manual/                 — mdBook user manual
          #   $out/api/rotating_secrets/   — ExDoc for rotating_secrets
          #   $out/api/vault/              — ExDoc for rotating_secrets_vault
          #   $out/api/testing/            — ExDoc for rotating_secrets_testing
          docs = pkgs.stdenv.mkDerivation {
            name = "rotating-secrets-docs";
            src = ./.;

            nativeBuildInputs = [
              elixir
              pkgs.git
              pkgs.mdbook
            ];

            buildPhase = ''
              export MIX_HOME="$TMPDIR/.mix"
              export HEX_HOME="$TMPDIR/.hex"
              export HOME="$TMPDIR"

              mix local.hex --force
              mix local.rebar --force

              # ExDoc: rotating_secrets (must build first; others depend on it)
              cd rotating_secrets
              mix deps.get
              mix docs
              cd ..

              # ExDoc: rotating_secrets_vault
              cd rotating_secrets_vault
              mix deps.get
              mix docs
              cd ..

              # ExDoc: rotating_secrets_testing
              cd rotating_secrets_testing
              mix deps.get
              mix docs
              cd ..

              # User manual
              mdbook build docs/book
            '';

            installPhase = ''
              mkdir -p $out/api/rotating_secrets
              mkdir -p $out/api/vault
              mkdir -p $out/api/testing
              mkdir -p $out/manual

              cp -r rotating_secrets/doc/. $out/api/rotating_secrets/
              cp -r rotating_secrets_vault/doc/. $out/api/vault/
              cp -r rotating_secrets_testing/doc/. $out/api/testing/
              cp -r docs/book/book/. $out/manual/

              cat > $out/index.html << 'INDEXEOF'
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <title>RotatingSecrets Documentation</title>
                <style>
                  body { font-family: sans-serif; max-width: 640px; margin: 4rem auto; padding: 0 1rem; }
                  h1 { font-size: 1.6rem; margin-bottom: 2rem; }
                  ul { list-style: none; padding: 0; }
                  li { margin: 1rem 0; }
                  a { font-size: 1.1rem; text-decoration: none; color: #2563eb; }
                  a:hover { text-decoration: underline; }
                  .subtitle { color: #6b7280; font-size: 0.9rem; margin-top: 0.2rem; }
                </style>
              </head>
              <body>
                <h1>RotatingSecrets Documentation</h1>
                <ul>
                  <li>
                    <a href="manual/index.html">User Manual</a>
                    <div class="subtitle">Guides, cookbook, telemetry, clustering, testing, troubleshooting</div>
                  </li>
                  <li>
                    <a href="api/rotating_secrets/index.html">API Reference — rotating_secrets</a>
                    <div class="subtitle">Core library: sources, registry, secret lifecycle</div>
                  </li>
                  <li>
                    <a href="api/vault/index.html">API Reference — rotating_secrets_vault</a>
                    <div class="subtitle">OpenBao / Vault KV v2 source</div>
                  </li>
                  <li>
                    <a href="api/testing/index.html">API Reference — rotating_secrets_testing</a>
                    <div class="subtitle">Controllable source and ExUnit helpers</div>
                  </li>
                </ul>
              </body>
              </html>
              INDEXEOF
            '';
          };

          # Utility to generate mix.nix from mix.lock
          # Run: nix run .#generate-mix-nix
          generate-mix-nix = pkgs.writeShellScriptBin "generate-mix-nix" ''
            if [ ! -f mix.lock ]; then
              echo "Error: mix.lock not found. Run 'mix deps.get' first."
              exit 1
            fi

            echo "Generating mix.nix from mix.lock..."
            ${pkgs.mix2nix}/bin/mix2nix > mix.nix
            echo "✓ Generated mix.nix"
            echo ""
            echo "Next steps:"
            echo "  1. Commit mix.nix to version control"
            echo "  2. Uncomment 'mixNix = ./mix.nix;' in flake.nix packages.default"
            echo "  3. Run 'nix build' to build with locked dependencies"
          '';
        };

        # Development shell with Elixir tools
        devShells.default = pkgs.mkShell {
          buildInputs = with pkgs; [
            # Elixir and Erlang
            elixir
            erlang

            # Hex and Rebar (required for dependencies, including GitHub repos)
            beamPackages.hex
            beamPackages.rebar3

            # mix2nix for generating mix.nix
            mix2nix

            # Development tools
            elixir-ls # Language server for IDE support
            git

            # Database clients
            postgresql # provides pg_ctl, initdb, pg_isready for local ephemeral DB tests
            openbao    # provides bao binary; test_helper.exs finds it via System.find_executable/1

            # Database clients (optional, uncomment if needed)
            # sqlite

            # Additional tools
            inotify-tools # For file watching (Phoenix live reload)
          ];

          shellHook = ''
            # Set up Mix directories
            export MIX_HOME="$PWD/.nix-mix"
            export HEX_HOME="$PWD/.nix-hex"
            mkdir -p "$MIX_HOME" "$HEX_HOME"

            # Add Mix binaries to PATH
            export PATH="$MIX_HOME/bin:$HEX_HOME/bin:$PATH"

            # Locale settings for Elixir
            export LANG=C.UTF-8
            export LC_ALL=C.UTF-8

            echo "🧪 Elixir Development Environment (with mix2nix)"
            echo "=============================================="
            echo ""
            echo "Elixir version: $(elixir --version | head -1)"
            echo "Erlang/OTP: $(erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell)"
            echo ""
            echo "Quick commands:"
            echo "  mix new <name>           - Create new Mix project"
            echo "  mix deps.get             - Fetch dependencies"
            echo "  mix compile              - Compile project"
            echo "  mix test                 - Run tests"
            echo "  mix test --cover         - Run tests with coverage"
            echo "  mix format               - Format code"
            echo "  mix credo                - Run static code analysis"
            echo "  mix credo --strict       - Run strict analysis"
            echo "  mix dialyzer             - Run type checker"
            echo "  mix release              - Build release"
            echo "  iex -S mix               - Start interactive shell"
            echo ""
            echo "mix2nix workflow:"
            echo "  mix2nix > mix.nix        - Generate mix.nix from mix.lock"
            echo "  nix run .#generate-mix-nix - Helper script to generate mix.nix"
            echo ""
            echo "Phoenix commands (if using Phoenix):"
            echo "  mix phx.new <name>       - Create Phoenix project"
            echo "  mix phx.server           - Start Phoenix server"
            echo "  mix ecto.create          - Create database"
            echo "  mix ecto.migrate         - Run migrations"
            echo ""
            echo "GitHub dependencies:"
            echo "  Add to mix.exs: {:dep, github: \"user/repo\"}"
            echo "  Then run: mix deps.get"
            echo ""
            echo "After adding/updating dependencies:"
            echo "  1. mix deps.get          - Fetch new dependencies"
            echo "  2. mix2nix > mix.nix     - Update Nix dependency manifest"
            echo "  3. git add mix.nix       - Commit updated manifest"
          '';
        };

        # App for running the built release
        apps = {
          default = flake-utils.lib.mkApp {
            drv = packages.default;
          };

          # Utility app to generate mix.nix
          generate-mix-nix = flake-utils.lib.mkApp {
            drv = packages.generate-mix-nix;
          };
        };
      }
    );
}
